### ISSUE TITLE
Crash on enabling optimal parts

### ISSUE THREAD

**Issue by TunaPatty** [Nepgearsy/Nepgearsy-HUD-Reborn#31]
Crash date: 04/03/2018 03:31:45 AM

PAYDAY 2 Crash log
Application has crashed: C++ exception
mods/Nepgearsy HUD Reborn/Classes/NepHudMenu.lua:881: attempt to index field 'ChangelogTextMenu' (a nil value)
SCRIPT STACK
RunCallback() 452
MousePressed() 73
MousePressed() 148
mouse_press() 387
lib/managers/mousepointermanager.lua:339
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
-------------------------------
Current thread: Main
-------------------------------
System information:
	Application version : 1.89.554.
	CPU : Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : Intel(R) HD Graphics 5500 / igdumdim32.dll[10.18.15.4274]
	Language : english
	Memory :     8101MB 1016KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers / Headphones (Realtek Audio))

Lua information
Lua Hook: present
BLT Hook data: present

Lua BLT Mods list
   Name: Ask Bot to Fix the Drill, Version: 10, Author: Dr_Newbie
   Name: Payday 2 BLT, Version: 2.0, Author: James Wilkinson
   Failed parsing mods.txt of Basic Voices, Message: After parsing a value an unexpected character was encountered: ". Path 'name', line 3, position 1.
   Name: BeardLib, Version: 2.9x, Author: GREAT BIG BUSHY BEARD & Luffy
   Name: Better Bots, Version: 39, Author: See readme
   Failed parsing mods.txt of Bot Bullet Collision Fixer, Message: After parsing a value an unexpected character was encountered: ". Path 'description', line 4, position 1.
   Name: Bullet Decapitations, Version: 10, Author: Undeadsewer
   Name: Community Items in Offline Mode, Version: 1.0, Author: OJSimpson
   Name: Delayed Calls Fix, Version: 0.0.1.2, Author: 
    Snh20
    James Wilkinson (original BLT implementation)
   Name: Dynamic Crosshairs, Version: 7, Author: Undeadsewer
   Name: Iter, Version: 78, Author: TdlQ
   Name: Jump and Duck in Casing Mode, Version: 1, Author: Dr_Newbie
   Name: Keepers, Version: 114, Author: TdlQ
    russian translation by chrom[K]a
   Name: Lobby Settings, Version: 12, Author: TdlQ
   Name: More Weapon Stats, Version: 35, Author: TdlQ, KarateF22 for all the code taken from Better Weapon Stats GUI
    chinese translation by CoolLKK
    thai translation by NewPJzuza
   Name: Mr. Dr. Fantastic!, Version: 4, Author: TdlQ
   Name: Lasers Plus, Version: 2.5, Author: Offyerrocker
   Name: No Flashbang Ringing, Version: 0.1, Author: Offyerrocker
   Name: Shake Removal, Version: 420, Author: Yamai
   Name: Pocohud Align/Sort/Colorize/Resize Crimenet Standalone, Version: 4, Author: name
   Name: Returnable Masks, Patterns and Materials, Version: 1.01, Author: McKillem, based on code by SC
   Failed parsing mods.txt of Simple Toggle Interaction, Message: After parsing a value an unexpected character was encountered: ". Path 'author', line 5, position 4.
   Name: Sliding, Version: 2, Author: Seven
   Name: Static Recoil, Version: 1, Author: Subsimple
   Name: ESCONDER O HUD MODIFIERS, Version: 1, Author: b2
   Name: Stop Taking Away My Toothbrush, Version: 1, Author: 2Cas
   Name: Stop the crimespree loss on crash, Version: , Author: Nepsy

**Comment by AzureeDev** [comment]
Thanks for the report, the new commit will fix this.
