### ISSUE TITLE
Big Lobby Crash

### ISSUE THREAD

**Issue by geicorules** [Nepgearsy/Nepgearsy-HUD-Reborn#43]
Anytime you have big lobby activated with more than vanilla amount of people ie more than 4 it crashes this doesn't happen with wolf hud.

I also found that having Biglobby activated makes you player info on bottom not show up either.

**Comment by AzureeDev** [comment]
Yes I am aware of this

But I cant stack player info when theres more than 4 cause the size of the panel is too big
Maybe Ill do something someday that will disable the allies panel if theres more than 4..
