### ISSUE TITLE
Random crash when joining an online lobby 

### ISSUE THREAD

**Issue by Amousu** [Nepgearsy/Nepgearsy-HUD-Reborn#47]
Application has crashed: C++ exception
mods/Sora's HUD Reborn/Hooks/HUD/HUDMissionBriefing.lua:105: attempt to index field 'hud' (a nil value)

SCRIPT STACK

Call() @mods/base/req/core/Hooks.lua:109
ProcessAllPeers() @mods/base/req/core/Networking.lua:189
ProcessChatString() @mods/base/req/core/Networking.lua:176
func() @mods/base/req/core/Networking.lua:165
Call() @mods/base/req/core/Hooks.lua:109
_receive_message() @mods/base/lua/ChatManager.lua:12
original() lib/managers/chatmanager.lua:68
receive_message_by_peer() @mods/base/req/core/Hooks.lua:260
lib/network/base/handlers/connectionnetworkhandler.lua:662

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.93.850
	CPU : AMD A6-9220 RADEON R4, 5 COMPUTE CORES 2C+3G (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon(TM) R4 Graphics / aticfx32.dll[21.19.414.1280]
	Language : english
	Memory :     3977MB 868KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speaker/Headphone (Realtek High Definition Audio))

**Comment by AzureeDev** [comment]
Never encountered so i'll close it for now
