### ISSUE TITLE
I can't see my bottom right hud that is the armour and health bar

### ISSUE THREAD

**Issue by ApplepunchorTracemaster** [Nepgearsy/Nepgearsy-HUD-Reborn#48]
Some reason I can't see my own health bar and armour I tried many way to figure out by changing setting on the mod and just having the Sora HUD Reborn mod. Nothing works. It's a shame I really like this hud.

https://i.imgur.com/aMwegi2.png

**Comment by AzureeDev** [comment]
must be a mod conflict.
