### ISSUE TITLE
HUD doesn't show up after loaded into the heist...

### ISSUE THREAD

**Issue by Nokthan** [Nepgearsy/Nepgearsy-HUD-Reborn#55]
After the latest update, the hud doesn't show up after getting into the heist. (as well as in options)
It still show up in the 'installed mods' however, no crash whatsoever, and only this mod has issue.
Here is the list of mods that I used:
- AdaptiveStreamingChunkSize
- BeardLib
- Borderless Windowed Updated
- corpse remover Goonmod Standalone
- Intro Cinematics Standalone
- Sora's HUD Reborn
- Stop the crimespree loss on crash
- The Fixes
- VanillaHUD Plus (I had followed the instruction to prevent crash with this mod, and was working perfectly fine before the latest update)
![mods](https://github.com/AzureeDev/Sora-HUD-Reborn/assets/138228323/f9861149-5131-44b5-bc8f-af43176622ee)

**Comment by AzureeDev** [comment]
do you have beardlib? it's necessary to have it

**Comment by Nokthan** [comment]
> do you have beardlib? it's necessary to have it

Yes.

**Comment by AzureeDev** [comment]
i don't see why it wouldn't work, it's fine on my end
check if you have mod options showing up
or else, send your BLT logs in `payday 2/mods/logs/`

**Comment by Nokthan** [comment]
Mod Options is there, however Sora's HUD reborn isn't there.
[2023_07_01_log.txt](https://github.com/AzureeDev/Sora-HUD-Reborn/files/11920044/2023_07_01_log.txt)

**Comment by Nokthan** [comment]
Here is how it looks like in game...
https://youtu.be/SP6VspfDXqE

**Comment by AzureeDev** [comment]
beardlib is not present

> [WARN] [BLT] Could not read or find mod.txt in mods/BeardLib/ 

so reinstall it and it should work

**Comment by Nokthan** [comment]
> beardlib is not present
> 
> > [WARN] [BLT] Could not read or find mod.txt in mods/BeardLib/
> 
> so reinstall it and it should work

Yeah I did that and it work now, thank you.
